version: '3.8'

services:
  app:
    image: guxian/docker-pull-in-web:latest
    container_name: docker-puller
    volumes:
      - ./downloads:/app/downloads
      - ./tmp:/app/tmp
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - ENABLE_CACHE=false
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
    restart: unless-stopped
    network_mode: host